apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: wildfly
spec:
  host: wildfly-<name>.apps.beopenit.eastus.aroapp.io
  tls:
    termination: edge
  to:
    kind: Service
    name: wildfly
